### ISSUE TITLE
System.out.println vervangen door logger

### ISSUE THREAD

**Issue by wietsedecnijf** [wietsedecnijf/Examen-Afstandsbediening#1]
Zou beter zijn moesten we de println vervangen door een logger waar er niveau's van weergave kan gebruikt worden.

**Comment by Jsalaets** [comment]
klinkt logisch, maar misschien eerst focussen op alle dingen dat de applicatie moet kunne en daarna alle println vervangen door logger?

**Comment by wietsedecnijf** [comment]
Uiteraard, ik zette het hier als reminder. Maar het gebruiken van Log4J staat als hint in de opgave
